classdef SpiresTimeInterpolator < handle
  % Takes the gap data produced by spiresGap and interpolate them temporally to
  % produce smoothed snow properties.
  properties
    pixelIsDone % array of progress of interpolating pixels, 0: not interpolated, 1:
      % interpolated.
    region % Regions obj.
    waterYearDate % WaterYearDate obj.
  end
  properties(Constant)
    defaultMonthWindow = 12;
    inputDataLabels = struct(mod09ga = 'modspiresdaily', vnp09ga = 'vnpspiresdaily');
    outputDataLabels = struct( ...
      mod09ga = 'modspiresyeartmp', vnp09ga = 'vnpspiresyeartmp');
  end
  methods
    function obj = SpiresTimeInterpolator(region, varargin)
      % Parameters
      % ----------
      % region: Regions obj. Modis tile only.
%{
      % waterYear: int, optional. Not used if waterYearDate supplied. By default,
      %   ongoing waterYear for the region.
      % waterYearDate: WaterYearDate, optional. By default, today waterYearDate if
      %   waterYear not supplied, or last date of waterYear if waterYear supplied.
%}
      thisFunction = 'SpiresTimeInterpolator.SpiresTimeInterpolator';
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      obj.region = region;
%{
      objectName = region.name;
      modisData = region.espEnv.modisData;
      defaultWaterYearDate = WaterYearDate(datetime(), ...
        modisData.getFirstMonthOfWaterYear(region.name), WaterYearDate.yearMonthWindow);
      defaultWaterYear = defaultWaterYearDate.getWaterYear();
      p = inputParser;
      addParameter(p, 'waterYear', defaultWaterYear);
      addParameter(p, 'waterYearDate', defaultWaterYearDate);
      p.StructExpand = false;
      parse(p, varargin{:});
      waterYear = p.Results.waterYear;
      obj.waterYearDate = p.Results.waterYearDate;
      if isequal(obj.waterYearDate, defaultWaterYearDate) && ...
        ~isequal(waterYear, defaultWaterYear)
        obj.waterYearDate = WaterYearDate(datetime(waterYear, ...
          modisData.getFirstMonthOfWaterYear(region.name), monthFirstDay) - days(1), ...
          modisData.getFirstMonthOfWaterYear(region.name), ...
          WaterYearDate.yearMonthWindow);
      end
      fprintf(['%s: Created SpiresTimeInterpolator, region: %s, waterYearDate: %s.\n'], ...
        thisFunction, region.name, obj.waterYearDate.toChar());
%}
      fprintf(['%s: Created SpiresTimeInterpolator, region: %s.\n'], ...
        thisFunction, region.name);
    end
    function interpolateForPixel(obj, waterYearDate, varargin)
       % Generate the spires smoothed data from the spires inversed data
      %   (generated by SpiresInversor).
      %   NB: Before launching this method, the interpolated fields must have been
      %   created in the smooth spires file. This creation is done by
      %   SpiresInversor.reset(), before the daily data are generated by
      %   SpiresInversor.calcForDate()
      %
      % Parameters
      % ----------
      % waterYearDate: WaterYearDate. Period over which the interpolation is done.
      % optim: struct(cellIdx, countOfCellPerDimension, force, logLevel,
      %       parallelWorkersNb).
      %   cellIdx: array(int), OBLIGATORY. [rowCellIdx, columnCellIdx].
      %       Indices of the cell part of a tile. Row indices are counted from
      %       top to bottom, column indices from left to right. Default [1, 1].
      %   countOfCellPerDimension: array(int), optional.
      %       [rowCellCount, columnCellCount]. Number of cells dividing the set of
      %       rows and same for columns. E.g. if we want to divide a 2400x2400
      %       tile in 9 cells, countOfCellPerDimension = [3, 3]. Default [1, 1].
      %   force: unused.
      %   logLevel: int, optional. Indicate the density of logs.
      %       Default 0, all logs. The higher the less logs.
      %   parallelWorkersNb: int, optional. If 0 (default), no parallelism.
      %
      % NB: in this method each variable data are handled as a time series of one pixel
      %   only, presented in 1 column.

      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Initialize and load variables and filters...
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      thisFunction = 'SpiresTimeInterpolator.interpolateForPixel';
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      espEnv = obj.region.espEnv;
      objectName = obj.region.name;
      theseDate = waterYearDate.getDailyDatetimeRange();
      defaultOptim = struct(cellIdx = [1, 1], ...
        countOfCellPerDimension = [ ...
        espEnv.modisData.sensorProperties.tiling.rowPixelCount, ...
        espEnv.modisData.sensorProperties.tiling.columnPixelCount], force = 0, ...
        logLevel = 0, ...
        parallelWorkersNb = 0);
      p = inputParser;
      addParameter(p, 'optim', struct());
      p.StructExpand = false;
      parse(p, varargin{:});
      optim = p.Results.optim;
      optimFieldNames = fieldnames(defaultOptim);
%{
      if length(optim.countOfCellPerDimension) == 2
        optim.countOfCellPerDimension = ...
          [optim.countOfCellPerDimension, length(theseDate)];
      end
%}
      for fieldIdx = 1:length(optimFieldNames)
        thisFieldName = optimFieldNames{fieldIdx};
        if ~ismember(thisFieldName, fieldnames(optim))
          optim.(thisFieldName) = defaultOptim.(thisFieldName);
        end
      end % fieldIx.
      fprintf(['%s: Starting, region: %s, waterYearDate: %s, ', ...
        'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
        'force: %d, logLevel: %d, ', ...
        'parallelWorkersNd: %d...\n'], thisFunction, obj.region.name, ...
        waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
        optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
        optim.force, optim.logLevel, optim.parallelWorkersNb);
      
      thisIndex = sub2ind(optim.countOfCellPerDimension, ...
        optim.cellIdx(1), optim.cellIdx(2));

      inputDataLabel =  obj.inputDataLabels.(espEnv.modisData.inputProduct);
      outputDataLabel =  obj.outputDataLabels.(espEnv.modisData.inputProduct);
        % We save the output in a temporary year file per pixel and per variable.
        % Another process will take the file and save the data in each modisspiresdaily
        % file.
      [variable, ~] = espEnv.getVariable(outputDataLabel, ...
        inputDataLabel = inputDataLabel);
      force = struct(dimensionInfo = 21);
        % to force values extracted from daily files to be in 1 column instead of 3D.

      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Filtering and interpolation parameters.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      parameterName = 'gapRareObservationSlidingWindowHalfSize';
      slidingWindowHalfSize = Tools.valueInTableForThisField( ...
        obj.region.filter.spires, 'lineName', ...
        parameterName, 'minValue');
        % in core.smoothSPIREScube() windowSize 40.
        % Must be < 122 days.
      parameterName = 'gapRareObservationMinDayWithObservationAboveMinValue';
      minimalDayWithObservationAboveMinimumValue = ...
        Tools.valueInTableForThisField( ...
          obj.region.filter.spires, 'lineName', ...
          parameterName, ...
          'minValue'); % in core.smoothSPIREScube() windowThresh 20.
          % Must be < 2 * slidingWindowHalfSize.

      snowFractionSetToZeroBelowThisValue = Tools.valueInTableForThisField( ...
        obj.region.filter.spires, 'lineName', ...
        'snowFractionSetToZeroBelowThisValue', 'minValue');
        % 10 fsca_thresh.
      smoothingDustSetToZeroBeforeGrainSizeMaxWhenBelowGrainSizeValue = ...
        Tools.valueInTableForThisField( ...
        obj.region.filter.spires, 'lineName', ...
        'smoothingDustSetToZeroBeforeGrainSizeMaxWhenBelowGrainSizeValue', 'minValue');
        % 300, dust_rg_thresh.
        % NB: data stored with divisor 0.1, its actually 3000.
      smoothingSplineParamForSnowAndDust = Tools.valueInTableForThisField( ...
        obj.region.filter.spires, 'lineName', ...
        'smoothingSplineParamForSnowAndDust', 'minValue');
        % 0.1 core.smoothSpiresCube() L143.
      smoothingSplineParamForGrainSize = Tools.valueInTableForThisField( ...
        obj.region.filter.spires, 'lineName', ...
        'smoothingSplineParamForGrainSize', 'minValue');
        % 0.8 core.smoothSpiresCube() L239.
      smoothingSplineMinimalCountOfPositiveObservation = ...
        Tools.valueInTableForThisField( ...
        obj.region.filter.spires, 'lineName', ...
        'smoothingSplineMinimalCountOfPositiveObservation', 'minValue');
        % 2 core.smoothDataCube() L173.

      % Peak fixing for grain size and dust
      peakFixingHampelToRemoveSpikeHalfWindow = ...
        Tools.valueInTableForThisField( ...
        obj.region.filter.spires, 'lineName', ...
        'peakFixingHampelToRemoveSpikeHalfWindow', 'minValue');
        % 2 in core.smoothSpiresCube() L209.
      peakFixingHampelToRemoveSpikeNSigma = ...
        Tools.valueInTableForThisField( ...
        obj.region.filter.spires, 'lineName', ...
        'peakFixingHampelToRemoveSpikeNSigma', 'minValue');
        % 2 in core.smoothSpiresCube() L209.
      peakFixingMaximalDurationInDay = ...
        Tools.valueInTableForThisField( ...
        obj.region.filter.spires, 'lineName', ...
        'peakFixingMaximalDurationInDay', 'minValue');
        % FixedDays = 40 days in core.smoothSPIREScube() L219;
      peakFixingDayWithoutCorrection = ...
        Tools.valueInTableForThisField( ...
        obj.region.filter.spires, 'lineName', ...
        'peakFixingDayWithoutCorrection', 'minValue');
        % 7 Nd number of days from the end of record to stop fixing peak.
        % in core.smoothSPIREScube() L223.
      peakFixingStartDay = ...
        Tools.valueInTableForThisField( ...
        obj.region.filter.spires, 'lineName', ...
        'peakFixingStartDay', 'minValue');
        % For NRT, don't do peak fixing before that day in waterYear, new for v2024.0e.
      lastDayOfPeakFixing = length(theseDate) - peakFixingDayWithoutCorrection;

      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Load filters for this pixel.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Exclude pixels without snow nansum=0, pixels with less than 2 days of
      % observation > 0 (i.e. including fsca thresh, rare obs, cloud, grain
      % tresh, water, isnan R0, elevation).

      % Filtering was previously partly done in core.fillMODIScube(),
      % core.run_spires(), core.smoothSPIREScube() and
      % TimeSpace.smoothDatacube().
      varName = 'daily_nodata_filter_s';
      [dailyNoDataFilter, waterYearDate] = espEnv.getDataForWaterYearDateAndVarName( ...
        objectName, inputDataLabel, waterYearDate, varName, force = force, ...
        optim = optim);
        % daily_not_nodata_filter: uint8, Bit, position 1: hasNoInput, 2: neuralCloud,
        % 3, backgroundReflectance nodata, 4: rareObservation.
        % waterYearDate is updated to restrict to the number of files we really have.
      theseDate = waterYearDate.getDailyDatetimeRange()';
      fprintf(['%s: Considered waterYearDate: %s...\n'], thisFunction, ...
        waterYearDate.toChar());

      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Days without observations and days since last observation...
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % NB: For this set of variable, an observation = 0 is considered an observation,
      % contrary to the subsequent set (moving persist).
      tic
      fprintf('Starting calcDaysWithoutObservations...\n');

      varName = 'days_since_last_observation_s';
      thisVariable = variable(strcmp(variable.name, varName), :);
      thisDaySince = ones(size(dailyNoDataFilter), thisVariable.type{1});

      % Determine which day is without observation.
      thisDaySince(~dailyNoDataFilter) = 0;
      thisDaySince = cast(thisDaySince, 'int16');
        % int16 to make diff, which can be negative.
      indicesForPeriods = cumsum([1; abs(diff(thisDaySince, 1, 1))]);
      isEqualSuccessiveIndicesForPeriods = ...
        int16([1; indicesForPeriods(1:end - 1, :)] == indicesForPeriods);
      indicesForPeriods = [];

      for rowIdx = 2:size(thisDaySince, 1)
        thisDaySince(rowIdx) = isEqualSuccessiveIndicesForPeriods(rowIdx) ...
          .* thisDaySince(rowIdx - 1) + thisDaySince(rowIdx);
      end

      thisDayWithout = thisDaySince;
      for rowIdx = size(thisDayWithout, 1) - 1: -1: 1
        thisDayWithout(rowIdx) = ...
          isEqualSuccessiveIndicesForPeriods(rowIdx + 1) ...
          .* thisDayWithout(rowIdx + 1) + ...
          int16(~isEqualSuccessiveIndicesForPeriods(rowIdx + 1)) ...
          .* thisDayWithout(rowIdx);
      end
      isEqualSuccessiveIndicesForPeriods = [];
      force.type = 'uint16';
      outputOptim = optim;
      outputOptim.cellIdx = [1, 1];
      outputOptim.countOfCellPerDimension = [1, 1];
      outputOptim.countOfPixelPerDimension = [1, 1];
      tic;
      espEnv.saveData(thisDaySince, objectName, ...
        outputDataLabel, theseDate = theseDate, thisIndex = thisIndex, ...
        varName = varName, ...
        optim = outputOptim, force = force);
        % NB: don't use the argument waterYearDate rather than theseDate, because
        % espEnv.saveData() don't accept optim when waterYearDate and cannot find one
        % file only in that case.                                               @warning
      fprintf(['%s: Saved %s in %.0f s, region: %s, waterYearDate: %s, ', ...
        'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
        'force: %d, logLevel: %d, ', ...
        'parallelWorkersNd: %d.\n'], thisFunction, varName, toc, obj.region.name, ...
        waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
        optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
        optim.force, optim.logLevel, optim.parallelWorkersNb);

      varName = 'days_without_observation_s';
      tic;
      espEnv.saveData(thisDayWithout, objectName, ...
        outputDataLabel, theseDate = theseDate, thisIndex = thisIndex, ...
        varName = varName, optim = outputOptim, force = force);
      fprintf(['%s: Saved %s in %.0f s, region: %s, waterYearDate: %s, ', ...
        'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
        'force: %d, logLevel: %d, ', ...
        'parallelWorkersNd: %d.\n'], thisFunction, varName, toc, obj.region.name, ...
        waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
        optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
        optim.force, optim.logLevel, optim.parallelWorkersNb);
      force = rmfield(force, 'type');

      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Calculation of Mask of rare observations above minimum value.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Here we calculate the number of days of observations (no clouds,
      % high snow fraction and high grain size) during a sliding time window. If
      % the number of observations is lower than a minimum (which is scaled to
      % the time window on both ends of the period), the observation is considered
      % rare observation and won't be considered in the interpolation.
      % core.smoothSPIREScube() L98 and core.movingPersist().

      % Determine the pixels/date in a period of rare observation, which may be
      % not considered reliable for later interpolation (used as a mask later).
      % RMQ: Not sure if this mask is really fair/appropriate. It works similarly
      % whether the observations are packed in a subperiod without observations
      % in the rest of the period or if observations are regularly spaced every
      % x over days. Additionally, it doesnt take into account the snowline of
      % the period of the year. Even if there's no observation during 10 days at
      % 2,000 meters in January in Washington state, it's probable that snow
      % didnt melt during that period.
      % Additionally, the mask only checks the count of days having high snow
      % fraction/high grain size, so it is more suspicious of high snow than of
      % low snow, and I think it's not well justified.              @toinvestigate

      % isObservation = ~isCloud | ~water | ~any(isnan(R0), 3)

      % Moving persist, which exclude some dates with rare observations...
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      fprintf('Starting movingPersist...\n');

      varName = 'daily_zero_filter_s';
      dailyZeroFilter = espEnv.getDataForWaterYearDateAndVarName( ...
        objectName, inputDataLabel, waterYearDate, varName, force = force, ...
        optim = optim);
        % daily_zero_filter: Bit, position 1: NeuralOther excluding state_1km.clouds
        % and including state_1km.saltpans, 2: NDSIBelowMinus005, 3: rawSnowBelow10,
        % 4: rawGrainBelow40, 5: lowElevation, 6: waterBody.
      isObservationAboveMinimum = ~dailyNoDataFilter & ~dailyZeroFilter;

      isNotRareObservation = isObservationAboveMinimum;
      for dateIdx = 1:numel(theseDate)
        nstart = max(1, dateIdx - slidingWindowHalfSize);
        nend = min(numel(theseDate), dateIdx + slidingWindowHalfSize);
        dayWithObservation = sum( ...
          isObservationAboveMinimum(nstart:nend, 1), 1);
          % 1: over each column. No nan here.
          % No cast from uint8 to uint16 if
          % slidingWindowHalfSize < intmax('uint8') / 2 (122 days).
        isNotRareObservationForTheDate = ...
          zeros(size(dayWithObservation), 'uint8');
        % Scaling of the minimal number of days such that it is
        % 1 * minimalDayWithObservationAboveMinimumValue for a full window and
        % 0.5 * minimalDayWithObservationAboveMinimumValue at start or end of
        % the period.
        scaledMinimalDaysWithObservation = (nend - nstart) / ...
          (2 * slidingWindowHalfSize) * ...
          minimalDayWithObservationAboveMinimumValue;
        isNotRareObservationForTheDate( ...
          dayWithObservation >= scaledMinimalDaysWithObservation) = 1;
        isNotRareObservation(dateIdx) = isNotRareObservationForTheDate;
      end

      % Update of dailyFilter bitwise variable and save it.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      dailyNoDataFilter = bitset(dailyNoDataFilter, 4, ~isNotRareObservation);

      varName = 'daily_nodata_filter_s';
      espEnv.saveData(thisDayWithout, objectName, ...
        outputDataLabel, theseDate = theseDate, thisIndex = thisIndex, ...
        varName = varName, optim = outputOptim, force = force);
      fprintf(['%s: Saved %s in %.0f s, region: %s, waterYearDate: %s, ', ...
        'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
        'force: %d, logLevel: %d, ', ...
        'parallelWorkersNd: %d.\n'], thisFunction, varName, toc, obj.region.name, ...
        waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
        optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
        optim.force, optim.logLevel, optim.parallelWorkersNb);

      snowToZero = dailyZeroFilter(:) | bitget(dailyNoDataFilter(:), 4);
      % RMQ: here snowToZero should be daily_zero_filter;       @toinvestigate
      % There's a problem here, since we set to 0
      % the rareObservationAboveMinimumValue and take them into account for
      % temporal interpolation.                                 @toinvestigate
      % NB: in the v2024.0 version, no data reflectance is also included, but there
      % was actually no nodata reflectance since all nodata were set to 0 when importing
      % reflectance from mod09ga MODIS_HDF.GetMOD09GA() L.70 and core.fillMODIScube()
      % L.215.

      toInterpolate = ~bitget(dailyNoDataFilter, 1) & ...
        ~bitget(dailyNoDataFilter, 2);
      % toInterpolate corresponds to the t = ~isnan(), that is the valid data that we
      % we can use for the interpolation.
      % TimeSpace.smoothDataCube() L176 and core.smoothSPIREScube() L134.
      % Instead of setting the data to NaN, we use ~toInterpolate
      % to exclude these non observations.
      % RMQ: here toInterpolate should be = uint8(dailyNoDataFilter == 2);
      % and include rareObservationAboveMinimumValue            @toinvestigate
      % NB: curiously ~toInterpolate also include 0 values...   @toinvestigate

      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Load weights for this pixel.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      varName = 'time_interp_weight_s'; % Weights.
      force.type = 'double';
      force.divisor = 0.01; % Obligatory (but not very obvious) to make operational the
        % real divisor in the configurationversionvariable.                     @warning
        % Not very well-carried out behavior, to correct.                          @todo
      weight = ...
        espEnv.getDataForWaterYearDateAndVarName(objectName, inputDataLabel, ...
        waterYearDate, varName,  force = force, optim = optim);
        % force convert to double and divide by 100.
      weight(isnan(weight)) = 0.01; % NB: maybe we could put this in nodata value.
      % Not necessary?                                                          @tocheck

      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Load, filter and interpolate viewable_snow_fraction for this pixel.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % snow_fraction (corrected will always have higher values than
      % viewable_snow_fraction and is nodata at the same places.
      % We can take advantage of the parfor loop to do both.
      % We limit the interpolation to the places where there actual data.
      % TimeSpace.smothDataCube() L228 and L231.
      varName = 'raw_viewable_snow_fraction_s';
      % viewable_snow_fraction (called raw_snow_fraction in version20231027).
      thisVariable = variable(strcmp(variable.name, varName), :);
      force.divisor = thisVariable.divisor(1);
      data = ...
        espEnv.getDataForWaterYearDateAndVarName(objectName, inputDataLabel, ...
        waterYearDate, varName,  force = force, optim = optim);
      data(snowToZero) = 0;
      data(~toInterpolate) = NaN;

      % Save gap variable.
      varName = 'gap_viewable_snow_fraction_s';
      espEnv.saveData(data, objectName, ...
        outputDataLabel, theseDate = theseDate, thisIndex = thisIndex, ...
        varName = varName, optim = outputOptim, force = force);
      fprintf(['%s: Saved %s in %.0f s, region: %s, waterYearDate: %s, ', ...
        'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
        'force: %d, logLevel: %d, ', ...
        'parallelWorkersNd: %d.\n'], thisFunction, varName, toc, obj.region.name, ...
        waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
        optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
        optim.force, optim.logLevel, optim.parallelWorkersNb);

      dataMin = min(data);
      dataMax = max(data);

      % Interpolated variable.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      varName = 'viewable_snow_fraction_s';
      thisVariable = variable(strcmp(variable.name, varName), :);

      pixelHasPositiveData = ~sum(data, 'omitnan') == 0 && ...
        nnz(data(toInterpolate)) >= ...
        smoothingSplineMinimalCountOfPositiveObservation;
      % TimeSpace.smoothDataCube() L173. We excluse
      % We exclude from interpolation the pixels that dont have any date
      % considered, that are full of nan (happens only for dust/grainsize)
      % or that have less than 2 > 0 observations.
      if ~pixelHasPositiveData
        data = zeros([length(theseDate), 1], thisVariable.type{1});
      else
        F = fit(double(1:length(theseDate))', data, ...
          'smoothingspline', weights = weight, exclude = ~toInterpolate, ...
          SmoothingParam = smoothingSplineParamForSnowAndDust);
        data = max(min(F(1:length(theseDate)), dataMax), dataMin);
        % Cap to raw data range (TimeSpace.smoothDataCube() L159&188, with
        % General.truncateLimits(). The second cap to min-max range of the
        % variable is not necessary (because done in SpiresInversor())
        data(data < snowFractionSetToZeroBelowThisValue) = 0;
          % < 10 core.smoothSPIREScube() L154.
      end
      espEnv.saveData(data, objectName, ...
        outputDataLabel, theseDate = theseDate, thisIndex = thisIndex, ...
        varName = varName, optim = outputOptim, force = force);
      fprintf(['%s: Saved %s in %.0f s, region: %s, waterYearDate: %s, ', ...
        'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
        'force: %d, logLevel: %d, ', ...
        'parallelWorkersNd: %d.\n'], thisFunction, varName, toc, obj.region.name, ...
        waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
        optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
        optim.force, optim.logLevel, optim.parallelWorkersNb);

      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Snow cover days.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % In v2024.0, there was two thresholds, on elevation >= 800 and on
      % snow_fration >= 10. The threshold 10 is kept
      % (snowFractionSetToZeroBelowThisValue) but not the elevation threshold
      % (currently just 500 for westernUS 2024-05-22.
      % NB: we can calculate days based on viewable_snow_fraction because (corrected)
      % snow_fraction is always equal or higher.                              @important
      varName = 'snow_cover_days_s';
      data = cumsum(data > 0);
      force = rmfield(force, 'divisor');
      espEnv.saveData(data, objectName, ...
        outputDataLabel, theseDate = theseDate, thisIndex = thisIndex, ...
        varName = varName, optim = outputOptim, force = force);
      fprintf(['%s: Saved %s in %.0f s, region: %s, waterYearDate: %s, ', ...
        'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
        'force: %d, logLevel: %d, ', ...
        'parallelWorkersNd: %d.\n'], thisFunction, varName, toc, obj.region.name, ...
        waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
        optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
        optim.force, optim.logLevel, optim.parallelWorkersNb);
%{
      % Not necessary any more, SpiresInversor makes sure the snow_fraction is above
      % ice fraction, except if ice fraction below 10.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Load complementary filters.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      varName = 'daily_other_filter';
      dailyOtherFilter = ...
        espEnv.getDataForWaterYearDateAndVarName(objectName, dataLabel, ...
        waterYearDate, varName, complementaryLabel, optim = optim);
      % daily_other_filter: 1: iceAbove10, 2: rawGrainAbove1190, 3:
      % dustAbove950.

      iceFraction = espEnv.getDataForObjectNameDataLabel(objectName, ...
        'iceFraction1D', optim = optim);

        % get the fice x 100;
      data(data < iceFraction(pixelIdx)) = iceFraction(pixelIdx);
        % core.smoothSPIREScube() L167.
      data(data < snowFractionSetToZeroBelowThisValue) = 0;
        % core.smoothSPIREScube() L154.
%}

      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Load, filter and interpolate (corrected_)snow_fraction for this pixel.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % NB: Same code as for viewable_snow_data.
      % We assume that corrected_snow_fraction is always higher than
      % viewable_snow_fraction and we could have keep the same value for
      % pixelHasPositiveData but we actually cannot because of the ice correction.
      varName = 'raw_snow_fraction_s';
      % true_snow_fraction (called snow_fraction in version20231027).
      thisVariable = variable(strcmp(variable.name, varName), :);
      force.divisor = thisVariable.divisor(1);
      data = ...
        espEnv.getDataForWaterYearDateAndVarName(objectName, inputDataLabel, ...
        waterYearDate, varName, force = force, optim = optim);
      data(snowToZero) = 0;
      data(~toInterpolate) = NaN;

      % Save gap variable.
      varName = 'gap_snow_fraction_s';
      espEnv.saveData(data, objectName, ...
        outputDataLabel, theseDate = theseDate, thisIndex = thisIndex, ...
        varName = varName, optim = outputOptim, force = force);
      fprintf(['%s: Saved %s in %.0f s, region: %s, waterYearDate: %s, ', ...
        'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
        'force: %d, logLevel: %d, ', ...
        'parallelWorkersNd: %d.\n'], thisFunction, varName, toc, obj.region.name, ...
        waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
        optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
        optim.force, optim.logLevel, optim.parallelWorkersNb);

      dataMin = min(data);
      dataMax = max(data);

      % Interpolated variable.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      varName = 'snow_fraction_s';
      % also called true_snow_fraction or corrected_snow_fraction.
      thisVariable = variable(strcmp(variable.name, varName), :);

      pixelHasPositiveData = ~sum(data, 'omitnan') == 0 && ...
        nnz(data(toInterpolate)) >= ...
        smoothingSplineMinimalCountOfPositiveObservation;

      % data(getbit(dailyOtherFilter, 1) & data > 0 & data < iceFraction) = iceFraction; % TOCHECK !!!!!!!!

      if ~pixelHasPositiveData
        data = zeros([length(theseDate), 1], thisVariable.type{1});
      else
        F = fit(double(1:length(theseDate))', data, ...
          'smoothingspline', weights = weight, ...
          exclude = ~toInterpolate, ...
          SmoothingParam = smoothingSplineParamForSnowAndDust);
        data = max(min(F(1:length(theseDate)), dataMax), dataMin);
        data(data < snowFractionSetToZeroBelowThisValue) = 0;
          % < 10 core.smoothSPIREScube() L154.
      end
      espEnv.saveData(data, objectName, ...
        outputDataLabel, theseDate = theseDate, thisIndex = thisIndex, ...
        varName = varName, optim = outputOptim, force = force);
      fprintf(['%s: Saved %s in %.0f s, region: %s, waterYearDate: %s, ', ...
        'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
        'force: %d, logLevel: %d, ', ...
        'parallelWorkersNd: %d.\n'], thisFunction, varName, toc, obj.region.name, ...
        waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
        optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
        optim.force, optim.logLevel, optim.parallelWorkersNb);

      isInterpolatedSnow = data > 0;

      % We update grain_size and dust only if there's snow, otherwise they stay at
      % no data and are not added to spiresyearlytmp pixel file.
      if any(isInterpolatedSnow > 0)
        varName = 'daily_grain_size_dust_s';
          % Bit, position 1: spatial interpolation of grain size, 2: grain size nodata
          % because below min, 3: grain size nodata because above max, 4: spatial
          % interpolation of dust concentration, 5: dust concentration nodata because
          % below min, 6: dust concentration nodata because above max.
        force = rmfield(force, {'type', 'divisor'});
        grainSizeDustFilter = ...
          espEnv.getDataForWaterYearDateAndVarName(objectName, inputDataLabel, ...
          waterYearDate, varName,  force = force, optim = optim);
        toInterpolate = toInterpolate(:) & isInterpolatedSnow(:) & ~snowToZero(:) & ...
          ~bitget(grainSizeDustFilter(:), 3) & ~bitget(grainSizeDustFilter(:), 6);
        % isInterpolatedSnow: positive interpolated snow.
        % ~snowToZero: positive raw (=inversed) snow. Means that we exclude
        % from the interpolation all dates that have no observed or
        % no interpolated snow.
        % In addition exclude high grain radius, high dust, and low grain radius
        % as in core.smoothSPIREScube() L179-193.

        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Load, filter and interpolate grain_radius (grain_size).
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % For grainsize and dust, we use a more elaborated method than
        % simple smoothing spline, to avoid physically impossible values
        % during melting.
        % Peak value. Avoids physically impossible retrievals such as shrinking
        % fsca and grain size due to increasing SWIR reflectance
        % set values after peak grain radius to peak (desc in
        % core.smoothSPIREScube() L27.
        % NB: Peak handling not performed on a ongoing wateryear which record
        % didn't end.                                                   @warning
        varName = 'raw_grain_size_s'; % grain_radius (also called grain_size).
        thisVariable = variable(strcmp(variable.name, varName), :);
        force.divisor = thisVariable.divisor(1);
        force.type = 'double';

        data = espEnv.getDataForWaterYearDateAndVarName(objectName, inputDataLabel, ...
          waterYearDate, varName, force = force, optim = optim);

        data(~toInterpolate) = NaN;

        % Save gap variable.
        varName = 'gap_grain_size_s';
        espEnv.saveData(data, objectName, ...
          outputDataLabel, theseDate = theseDate, thisIndex = thisIndex, ...
          varName = varName, optim = outputOptim, force = force);
        fprintf(['%s: Saved %s in %.0f s, region: %s, waterYearDate: %s, ', ...
          'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
          'force: %d, logLevel: %d, ', ...
          'parallelWorkersNd: %d.\n'], thisFunction, varName, toc, obj.region.name, ...
          waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
          optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
          optim.force, optim.logLevel, optim.parallelWorkersNb);

        % Interpolated variable.
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        varName = 'grain_size_s';
        % also called grain_radius.
        thisVariable = variable(strcmp(variable.name, varName), :);

        % Get rid of spikes & drops
        % NB: replace some no data by values...                                 @warning
        data = hampel(data, ...
          peakFixingHampelToRemoveSpikeHalfWindow, ...
          peakFixingHampelToRemoveSpikeNSigma);
        % set 1st day to min, may be set to nan later, but helps keeping
        % spline in check.
        data(1) = thisVariable.min(1);

        % Peak fixing cannot last more than N days from final peak.
        % Get the max after all days prior to
        % meltOutday - peakFixingMaximalDurationInDay, with meltOutday = last day with
        % snow, or end of waterYear.
        % NB: Peak fixing for ongoing NRT water year only after peakFixingStartDay and
        % without the taper at the end.

        % We don't taper to minimum if waterYear in NRT. Seb 20240524.
        if length(theseDate) < WaterYearDate.getCountOfDayInWaterYear(theseDate(1), ...
          obj.region.myConf.region.firstMonthOfWaterYear)
          peakFixingDayWithoutCorrection = 0;
          lastDayOfPeakFixing = length(theseDate);
        end
        % For waterYear NRT, we fix the maximum for the last days only in melting season
        % (fixed in configuration). Seb 20240524.
        if length(theseDate) < peakFixingStartDay
          maxDay = length(theseDate) + 1;
        else
          meltOutday = min(find(toInterpolate, 1, 'last'), ...
            length(theseDate));
          [~, maxDay] = max( ...
            data(meltOutday - peakFixingMaximalDurationInDay + 1:meltOutday), [], ...
            'omitnan'); % max day should be >= 2! warning
          maxDay = maxDay + meltOutday - peakFixingMaximalDurationInDay;
        end

        % Interpolation of 3 distinct periods.
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        if sum(data, 'omitnan') == 0 || nnz(toInterpolate(1:maxDay - 1)) < 2
          data = zeros([length(theseDate), 1], thisVariable.type{1});
        else
          % Period 1: before melting and the last day of max grain size
          % smooth up to maxDay. % core.smoothVector()
          F = fit(double(1:maxDay - 1)', double(data(1:maxDay - 1)), ...
            'smoothingspline', ...
            weights = double([1; weight(2:maxDay - 1)]), ...
            exclude = [0; ~toInterpolate(2:maxDay - 1)], ...
            SmoothingParam = smoothingSplineParamForGrainSize);
            % put the 1st day weight 1 so that the spline be controlled by
            % that day.
          data(1:maxDay - 1) = F(double(1:maxDay - 1)');

          % Period 2: between the of max grain size and the last day of peak
          % fixing. Set those days to (near) max grain size.
          if maxDay <= length(theseDate)
            data(maxDay:lastDayOfPeakFixing) = data(maxDay);
          end

          % Period 3: after peak fixing.
          % taper vector to min value using a spline with 2 points
          % core.taperVector()
          if lastDayOfPeakFixing < length(theseDate)
            data(lastDayOfPeakFixing + 1:end) = thisVariable.min(1);
            if isnan(data(lastDayOfPeakFixing))
              data(lastDayOfPeakFixing) = thisVariable.min(1);
            elseif data(lastDayOfPeakFixing) ~= thisVariable.min(1)
              F = spline( ...
                [length(theseDate) - peakFixingDayWithoutCorrection, ...
                length(theseDate)], ...
                [0 [data(lastDayOfPeakFixing), thisVariable.min(1)] 0]);
              data(lastDayOfPeakFixing:end) = ...
                fnval(F, lastDayOfPeakFixing:length(data));
            end
          end % if lastDayOfPeakFixing < length(theseDate)
        end % if sum(data, 'omitnan') == 0 || nnz(toInterpolate) < 2
        data = max(min(data, thisVariable.max(1)), thisVariable.min(1));
        % Contrary to snow, we dont cap based on raw data.
        data(~isInterpolatedSnow) = NaN;
        espEnv.saveData(data, objectName, ...
          outputDataLabel, theseDate = theseDate, thisIndex = thisIndex, ...
          varName = varName, optim = outputOptim, force = force);
        fprintf(['%s: Saved %s in %.0f s, region: %s, waterYearDate: %s, ', ...
          'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
          'force: %d, logLevel: %d, ', ...
          'parallelWorkersNd: %d.\n'], thisFunction, varName, toc, obj.region.name, ...
          waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
          optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
          optim.force, optim.logLevel, optim.parallelWorkersNb);
        isLowGrainSize = data <= ...
          smoothingDustSetToZeroBeforeGrainSizeMaxWhenBelowGrainSizeValue;
          % dust_rg_thresh.
        grainSize = data; % used to calculate albedo/deltavis/radiative_forcing.

        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Load, filter and interpolate dust (dust_concentration).
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        varName = 'raw_dust_concentration_s';
        % dust (also called dust_concentration).
        thisVariable = variable(strcmp(variable.name, varName), :);
        force.divisor = thisVariable.divisor(1);
        data = espEnv.getDataForWaterYearDateAndVarName(objectName, inputDataLabel, ...
          waterYearDate, varName,  force = force, optim = optim);

        data(~toInterpolate) = NaN;

        % Save gap variable.
        varName = 'gap_dust_concentration_s';
        espEnv.saveData(data, objectName, ...
          outputDataLabel, theseDate = theseDate, thisIndex = thisIndex, ...
          varName = varName, optim = outputOptim, force = force);
        fprintf(['%s: Saved %s in %.0f s, region: %s, waterYearDate: %s, ', ...
          'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
          'force: %d, logLevel: %d, ', ...
          'parallelWorkersNd: %d.\n'], thisFunction, varName, toc, obj.region.name, ...
          waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
          optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
          optim.force, optim.logLevel, optim.parallelWorkersNb);

        % Interpolated variable.
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        varName = 'dust_concentration_s';
        % also called dust.
        thisVariable = variable(strcmp(variable.name, varName), :);
        % set 1st day to min, may be set to nan later, but helps keeping
        % spline in check.
        data(1) = thisVariable.min(1);

        % NB/Reminder: Peak fixing for ongoing NRT water year only after
        % peakFixingStartDay and without the taper at the end.
        if maxDay < length(theseDate)
          % Set dust for all days prior the day of max grain size to 0 if
          % below grain threshold. core.smoothSPIREScube() L247-251.
          data([true([maxDay - 1, 1]); ...
            false([length(theseDate) - maxDay + 1, 1])] & isLowGrainSize) = 0;
        else
           data(isLowGrainSize) = 0;
        end

        % Interpolation of 3 distinct periods.
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        if sum(data, 'omitnan') == 0 || nnz(toInterpolate(1:maxDay - 1)) < 2
          data = zeros([length(theseDate), 1], thisVariable.type{1});
        else
          % Period 1: before melting and the last day of max grain size
          % smooth up to maxDay. % core.smoothVector()
          F = fit(double(1:maxDay - 1)', double(data(1:maxDay - 1)), ...
            'smoothingspline', ...
            weights = double([1; weight(2:maxDay - 1)]), ...
            exclude = [0; ~toInterpolate(2:maxDay - 1)], ...
            SmoothingParam = smoothingSplineParamForSnowAndDust);
            % put the 1st day weight 1 so that the spline be controlled by
            % that day.
          data(1:maxDay - 1) = F(double(1:maxDay - 1)');

          % Period 2: between the of max grain size and the last day of peak
          % fixing.
          % set dust after those days to value on maxday
          if maxDay <= length(theseDate)
            data(maxDay:lastDayOfPeakFixing) = data(maxDay);
          end

          % Period 3: after peak fixing.
          % taper vector to min value using a spline with 2 points
          % core.taperVector()
          if lastDayOfPeakFixing < length(theseDate)
            data(lastDayOfPeakFixing + 1:end) = thisVariable.min(1);
            if isnan(data(lastDayOfPeakFixing))
              data(lastDayOfPeakFixing) = thisVariable.min(1);
            elseif data(lastDayOfPeakFixing) ~= thisVariable.min(1)
              F = spline( ...
                [length(theseDate) - peakFixingDayWithoutCorrection, ...
                length(theseDate)], ...
                [0 [data(lastDayOfPeakFixing), thisVariable.min(1)] 0]);
              data(lastDayOfPeakFixing:end) = ...
                fnval(F, lastDayOfPeakFixing:length(data));
            end
          end % if lastDayOfPeakFixing < length(theseDate)
        end  % if sum(data, 'omitnan') == 0 || nnz(toInterpolate) < 2

        data = max(min(data, thisVariable.max(1)), thisVariable.min(1));
        data(~isInterpolatedSnow) = NaN;
        espEnv.saveData(data, objectName, ...
          outputDataLabel, theseDate = theseDate, thisIndex = thisIndex, ...
          varName = varName, optim = outputOptim, force = force);
        fprintf(['%s: Saved %s in %.0f s, region: %s, waterYearDate: %s, ', ...
          'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
          'force: %d, logLevel: %d, ', ...
          'parallelWorkersNd: %d.\n'], thisFunction, varName, toc, obj.region.name, ...
          waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
          optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
          optim.force, optim.logLevel, optim.parallelWorkersNb);
        dustConcentration = data;
      end % if any(isInterpolatedSnow > 0)
    end
    function interpolateForWaterYearDate(obj, waterYearDate, varargin)
      % Generate the spires smoothed data from the spires inversed data
      %   (generated by SpiresInversor).
      %   NB: Before launching this method, the interpolated fields must have been
      %   created in the smooth spires file. This creation is done by
      %   SpiresInversor.reset(), before the daily data are generated by
      %   SpiresInversor.calcForDate()
      %
      % Parameters
      % ----------
      % waterYearDate: WaterYearDate. Period over which the interpolation
      %       is done.
      % optim: struct(cellIdx, countOfCellPerDimension, force, logLevel,
      %       parallelWorkersNb).
      %   cellIdx: array(int), optional. [rowCellIdx, columnCellIdx].
      %       Indices of the cell part of a tile. Row indices are counted from
      %       top to bottom, column indices from left to right. Default [1, 1].
      %   countOfCellPerDimension: array(int), optional.
      %       [rowCellCount, columnCellCount]. Number of cells dividing the set of
      %       rows and same for columns. E.g. if we want to divide a 2400x2400
      %       tile in 9 cells, countOfCellPerDimension = [3, 3]. Default [1, 1].
      %   force: unused.
      %   logLevel: int, optional. Indicate the density of logs.
      %       Default 0, all logs. The higher the less logs.
      %   parallelWorkersNb: int, optional. If 0 (default), no parallelism.
      %
      % NB: All variables interpolated output is saved in fields that should exist
      %   in the daily files and instantiated to 0 or nodata.

      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Initialize and load variables and filters...
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      thisFunction = 'SpiresTimeInterpolator.interpolateForWaterYearDate';
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      espEnv = obj.region.espEnv;
      objectName = obj.region.name;
      defaultOptim = struct(cellIdx = [1, 1], ...
        countOfCellPerDimension = [1, 1], force = 0, logLevel = 0, ...
        parallelWorkersNb = 0);
      p = inputParser;
      addParameter(p, 'optim', struct());
      p.StructExpand = false;
      parse(p, varargin{:});
      optim = p.Results.optim;
      optimFieldNames = fieldnames(defaultOptim);
      for fieldIdx = 1:length(optimFieldNames)
        thisFieldName = optimFieldNames{fieldIdx};
        if ~ismember(thisFieldName, fieldnames(optim))
          optim.(thisFieldName) = defaultOptim.(thisFieldName);
        end
      end % fieldIx.

      fprintf(['%s: Starting, region: %s, waterYearDate: %s, ', ...
        'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
        'force: %d, logLevel: %d, ', ...
        'parallelWorkersNd: %d...\n'], thisFunction, obj.region.name, ...
        waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
        optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
        optim.force, optim.logLevel, optim.parallelWorkersNb);
      
      % Correction of waterYearDate with overlap over previous year if ongoing water
      % year too short.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      parameterName = 'interpOverlapMonthWindow';
      interpOverlapMonthWindow = Tools.valueInTableForThisField( ...
        obj.region.filter.spires, 'lineName', ...
        parameterName, 'minValue');
        % a period of x (e.g. 3) months from the previous year is added
        % to the dataset to be used for interpolation, to avoid making interpolation on
        % a too short period, potentially full of no data because of clouds.
      parameterName = 'interpMonthWindowBelowWhichOverlapIsRequired';
      interpMonthWindowBelowWhichOverlapIsRequired = Tools.valueInTableForThisField( ...
        obj.region.filter.spires, 'lineName', ...
        parameterName, 'minValue');
        % Below this number of months (e.g. 6 months), an
        % overlap with the previous waterYear is used for interpolation.
        % NB: this can't work if we don't have data of at least a full first waterYear.
        %                                                                       @warning
      if waterYearDate.monthWindow <= interpMonthWindowBelowWhichOverlapIsRequired
        waterYearDate = WaterYearDate(waterYearDate.thisDatetime, ...
          waterYearDate.firstMonth, ...
          waterYearDate.monthWindow + interpOverlapMonthWindow, ...
          dateOfToday = waterYearDate.dateOfToday, overlapOtherYear = 1);
        fprintf(['%s: Force waterYearDate to overlap previous water year: %s.\n'], ...
          thisFunction, waterYearDate.toChar());
      end

      tic;
      dataLabel =  obj.inputDataLabels.(espEnv.modisData.inputProduct);
      [~, ~, ~, waterYearDate] = espEnv.getFilePathForWaterYearDate(objectName, ...
        dataLabel, waterYearDate);
      espEnv.lastCallToGetFilePathForWaterYearDate.waterYearDate = waterYearDate;
        % waterYearDate until last day where there are modisspiresdaily files.
      theseDate = waterYearDate.getDailyDatetimeRange();
      % Get list of pixels to handle.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      force = struct();
      [startIdx, endIdx, thisSize] = espEnv.getIndicesForCellForDataLabel( ...
        objectName, dataLabel, force = force, optim = optim);
      thisTileSize = [espEnv.modisData.sensorProperties.tiling.rowPixelCount, ...
        espEnv.modisData.sensorProperties.tiling.columnPixelCount];
        % Size of full tile here.
      pixelIndices = sub2ind(thisTileSize, ...
        repmat((startIdx(1):endIdx(1))', [1, thisSize(2)]), ...
        repmat(startIdx(2):endIdx(2), [thisSize(1), 1]));
        % Assuming a classic row x column raster.

      % %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Load filters for this pixel and remove pixels not to interpolate.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % This is a first removal, another is done within .interpolateForPixel()
      % Exclude pixels in water, with isnan R0, low elevation.
      % We only take the first date, this value is the same for all dates.

      % Filtering was previously partly done in core.fillMODIScube(),
      % core.run_spires(), core.smoothSPIREScube() and
      % TimeSpace.smoothDatacube().
      varName = 'daily_nodata_filter_s';
      complementaryLabel = '';
      dailyNoDataFilter = espEnv.getDataForDateAndVarName( ...
        objectName, dataLabel, theseDate(1), varName, complementaryLabel, ...
        optim = optim);
        % daily_nodata_filter: uint8, Bit, position 1: hasNoInput, 2: neuralCloud,
        % 3, backgroundReflectance nodata, 4: rareObservation.

      varName = 'daily_zero_filter_s';
      dailyZeroFilter = ...
        espEnv.getDataForDateAndVarName(objectName, dataLabel, ...
        theseDate(1), varName, complementaryLabel, optim = optim);
        % daily_zero_filter: Bit, position 1: NeuralOther excluding state_1km.clouds
        % and including state_1km.saltpans, 2: NDSIBelowMinus005, 3: rawSnowBelow10,
        % 4: rawGrainBelow40, 5: lowElevation, 6: waterBody.
      pixelIndices = pixelIndices(~bitget(dailyNoDataFilter, 3) & ...
        ~bitget(dailyZeroFilter, 5) & ~bitget(dailyZeroFilter, 6));

      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Filtering and temporal interpolation (smoothing) by pixel
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Compared to core.smoothSPIREScube(), we put all variables in the same
      % parfor, we should gain in performance and time.
      % NB: this parfor load data pixel by pixel. We probably lose time by doing this
      % rather than loading the full matrices, but this probably lowe memory consumption
      % so that we can increase parallelization.
      obj.pixelIsDone = zeros([length(pixelIndices), 1], 'uint8');
      fprintf(['%s - Start of interpolation of %d pixels...\n'], ...
        char(datetime(), 'hh:mm:ss'), length(pixelIndices));
      thisDataQueue = parallel.pool.DataQueue;
      afterEach(thisDataQueue, @obj.printPixelIsDone);
      parfor idxInPixelIndices = 1:length(pixelIndices)
        thisOptim = optim;
        [thisOptim.cellIdx(1), thisOptim.cellIdx(2)] = ...
          ind2sub(thisTileSize, pixelIndices(idxInPixelIndices));
        thisOptim.countOfCellPerDimension = thisTileSize;
        obj.interpolateForPixel(waterYearDate, optim = thisOptim);
        % NB: We are forced by matlab to create a method .interpolateForPixel(),
        % otherwise the current implementation of matlab doesnt find the correct
        % classication of the sliced variables.
        send(thisDataQueue, idxInPixelIndices);
      end % for idxInPixelIndices.

      toc
      fprintf(['%s: Done, region: %s, waterYearDate: %s, ', ...
        'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
        'force: %d, logLevel: %d, ', ...
        'parallelWorkersNd: %d...\n'], thisFunction, obj.region.name, ...
        waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
        optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
        optim.force, optim.logLevel, optim.parallelWorkersNb);
    end
    function printPixelIsDone(obj, idxInPixelIndices)
      obj.pixelIsDone(idxInPixelIndices) = 1;
      sumOfPixelIsDone = sum(obj.pixelIsDone);
      if mod(sumOfPixelIsDone, 100) == 0
        fprintf(['%s - %d/%d interpolated...\n'], char(datetime(), 'hh:mm:ss'), ...
          sumOfPixelIsDone, length(obj.pixelIsDone));
      end
    end
    function calcNotRareObservationAboveMinimumValue(obj, varargin)
      % Determine the pixels/date in a period of rare observation, which may be
      % not considered reliable for later interpolation (used as a mask later).
      %
      % Parameters
      % ----------
      % waterYearDate: waterYearDate obj. By default the waterYearDate of the
      %   current waterYear and today's date.
      % optim: struct(cellIdx, countOfCellPerDimension, force, logLevel,
      %       parallelWorkersNb).
      %   cellIdx: array(int), optional. [rowCellIdx, columnCellIdx].
      %       Indices of the cell part of a tile. Row indices are counted from
      %       top to bottom, column indices from left to right. Default [1, 1].
      %   countOfCellPerDimension: array(int), optional.
      %       [rowCellCount, columnCellCount]. Number of cells dividing the set of
      %       rows and same for columns. E.g. if we want to divide a 2400x2400
      %       tile in 9 cells, countOfCellPerDimension = [3, 3]. Default [1, 1].
      %   force: unused.
      %   logLevel: int, optional. Indicate the density of logs.
      %       Default 0, all logs. The higher the less logs.
      %   parallelWorkersNb: int, optional. If 0 (default), no parallelism.
      %
      % RMQ: Not sure if this mask is really fair/appropriate. It works similarly
      % whether the observations are packed in a subperiod without observations
      % in the rest of the period or if observations are regularly spaced every
      % x over days. Additionally, it doesnt take into account the snowline of
      % the period of the year. Even if there's no observation during 10 days at
      % 2,000 meters in January in Washington state, it's probable that snow
      % didnt melt during that period.
      % Additionally, the mask only checks the count of days having high snow
      % fraction/high grain size, so it is more suspicious of high snow than of
      % low snow, and I think it's not well justified.              @toinvestigate

      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Initialize and load variables and filters...
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      thisFunction = 'SpiresInversor.calcRareObservationAboveMinimumValue';
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      espEnv = obj.region.espEnv;
      objectName = obj.region.name;
      theseDates = waterYearDate.getDailyDatetimes();
      defaultOptim = struct(cellIdx = [1, 1], ...
        countOfCellPerDimension = [1, 1], force = 0, logLevel = 0, ...
        parallelWorkersNb = 0);
      addParameter(p, 'optim', struct());
      p.StructExpand = false;
      parse(p, varargin{:});
      optim = p.Results.optim;
      optimFieldNames = fieldnames(defaultOptim);
      for fieldIdx = 1:length(optimFieldNames)
        thisFieldName = optimFieldNames{fieldIdx};
        if ~ismember(thisFieldName, fieldnames(optim))
          optim.(thisFieldName) = defaultOptim.(thisFieldName);
        end
      end % fieldIx.
      fprintf(['%s: Starting, region: %s, waterYearDate: %s, ', ...
        'cellIdx: [%d, %d], countOfCellPerDimension: [%d, %d], ', ...
        'force: %d, logLevel: %d, ', ...
        'parallelWorkersNd: %d...\n'], thisFunction, obj.region.name, ...
        waterYearDate.toChar(), optim.cellIdx(1), optim.cellIdx(2), ...
        optim.countOfCellPerDimension(1), optim.countOfCellPerDimension(2), ...
        optim.force, optim.logLevel, optim.parallelWorkersNb);

      tic;
      indices = espEnv.modisData.getIndicesForCellInTile(optim.cellIdx, ...
          optim.countOfCellPerDimension);

      dataLabel = 'modisspiresmat';

      [outputVariable, ~] = espEnv.getVariable(dataLabel);

      spatialSize = [espEnv.modisData.sensorProperties.rowPixelCount, ...
        espEnv.modisData.sensorProperties.columnPixelCount];

      data = struct();
      % bit mask which filters (remove) the unreliable
        % data are directly stored in modisspiresmat 2D with 1st D index of the
        % pixel and 2nd D day of waterYear.
        % only the data having permanent_filter >= 1 are stored (i.e. we also
        % store elevationBelow500 but not water)
        % so we can reconstruct the 3D (3rd dim: time) by the permanent 2D
        % filter ( row: north south, column: west east).
        % 2D daily_filter different from permanent_filter 1D
        % permanent_filter: uint8, 1: land, 2: elevationAbove500
        % ( 2 elevation, 3 elevation + land). We suppose no ~any(isnan(R0), 3)
        % and % there's no nan R because NaN are corrected to 0 previously.
        % daily_not_nodata_filter: uint8, position 1: hasInput,
        % 2: notNeuralCloud, 3: notRareObservationAboveMinimumValue.
        % daily_zero_filter: 1: NeuralOther, 2: NDSIBelowMinus005,
        % 3: rawSnowBelow10 4: rawGrainBelow40
        % daily_other_filter: 1: iceAbove10, 2: rawGrainAbove1190, 3:
        % dustAbove950.

      complementaryLabel = '';
      varName = 'not_nodata_filter';
      dailyNotNoDataFilter = espEnv.getDataForWaterYearDateAndVarName( ...
        objectName, dataLabel, waterYearDate, varName, complementaryLabel);
      varName = 'zero_filter';
      dailyZeroFilter = espEnv.getDataForWaterYearDateAndVarName( ...
        objectName, dataLabel, waterYearDate, varName, complementaryLabel);

      % Calculation of Mask of rare observations above minimum value.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % Here we calculate the number of days of observations (no clouds,
      % high snow fraction and high grain size) during a sliding time window. If
      % the number of observations is lower than a minimum (which is scaled to
      % the time window on both ends of the period), the observation is considered
      % rare observation and won't be considered in the interpolation.
      % core.smoothSPIREScube() L98 and core.movingPersist().

      % isObservation = ~isCloud | ~water | ~any(isnan(R0), 3)
      fprintf('Starting movingPersist...\n');
      tic
      isObservationAboveMinimum = uint8(bitget(dailyNotNoDataFilter, 1) & ...
        ~(bitget(~dailyZeroFilter, 1) | bitget(~dailyZeroFilter, 2) | ...
        bitget(dailyFilter, 3) | bitget(dailyFilter, 4)));

      parameterName = 'gapRareObservationSlidingWindowHalfSize';
      slidingWindowHalfSize = Tools.valueInTableForThisField( ...
        obj.region.filter.spires, 'lineName', ...
        parameterName, 'minValue');
        % in core.smoothSPIREScube() windowSize 40.
        % Must be < 122 days.
      parameterName = 'gapRareObservationMinDayWithObservationAboveMinValue';
      minimalDayWithObservationAboveMinimumValue = ...
        Tools.valueInTableForThisField( ...
          obj.region.filter.spires, 'lineName', ...
          parameterName, ...
          'minValue'); % in core.smoothSPIREScube() windowThresh 20.
          % Must be < 2 * slidingWindowHalfSize.
      isNotRareObservation = isObservationAboveMinimum;
      for dateIdx = 1:size(theseDates)
        nstart = max(1, dateIdx - slidingWindowHalfSize);
        nend = min(size(theseDates), dateIdx + slidingWindowHalfSize);
        dayWithObservation = sum( ...
          isObservationAboveMinimum(:, :, nstart:nend), 1);
          % 1: over each column. No nan here.
          % No cast from uint8 to uint16 if
          % slidingWindowHalfSize < intmax('uint8') / 2 (122 days).
        isNotRareObservationForTheDate = ...
          zeros(size(dayWithObservation), 'uint8');
        % Scaling of the minimal number of days such that it is
        % 1 * minimalDayWithObservationAboveMinimumValue for a full window and
        % 0.5 * minimalDayWithObservationAboveMinimumValue at start or end of
        % the period.
        scaledMinimalDaysWithObservation = (nend - nstart) / ...
          (2 * slidingWindowHalfSize) * ...
          minimalDayWithObservationAboveMinimumValue;
        isNotRareObservationForTheDate( ...
          dayWithObservation >= scaledMinimalDaysWithObservation) = 1;
        isNotRareObservation(dateIdx, :) = isNotRareObservationForTheDate;
      end

      % Update of dailyFilter bitwise variable and save it.
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      dailyNoDataFilter = bitset(dailyNoDataFilter, 2, isRareObservation);

      espEnv.saveDataForWaterYearDateAndVarName( ...
        dailyNoDataFilter, objectName, ...
        dataLabel, waterYearDate, varName, complementaryLabel);
      fprintf(['%s: Done in %.0f, region: %s, waterYearDate: %s, ', ...
        'cellIdx: %d, countOfCells: %d, force: %d, logLevel: %d, ', ...
        'parallelWorkersNd: %d...\n'], thisFunction, toc, obj.region.name, ...
        waterYearDate.toChar(), optim.cellIdx, optim.countOfCells, ...
        optim.force, optim.logLevel, optim.parallelWorkersNb);
    end
  end
end
